name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - PSaiSoumya-patch-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
        env:
          CI: true

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@PSaiSoumya-patch-2
        with:
          args: -avz --delete
          exclude: ".git"
          source: "build/"
          host: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
          repo-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          user: ${{ secrets.LIGHTSAIL_SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          target: "/var/www/html"
          

