name: UI Deployment

# In this section, two enivorment variables are created which will be use in the section of the configuration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the production branch
  push:
    branches: PSaiSoumya-patch-2

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on 
    runs-on: ubuntu-latest

    steps:
      - name: git clone https://github.com/PSaiSoumya/simple-reactjs-app.git
        uses: actions/checkout@v2

      - name: Install And Build Our React App
        run: npm install && npm run build

      - name: Deploy to Lightsail
        uses: appleboy/scp-action@v2.4.0
        with:
          host: ${{ secrets.LIGTHSAIL_IP }}
          username: ${{ secrets.LIGTHSAIL_USERNAME }}
          key: ${{ secrets.LIGTHSAIL_KEY }}
          password: ""
          passphrase: ""
          port: 22
          target: "/home/${{ secrets.LIGTHSAIL_USERNAME }}"

      - name: Connect to AWS Lightsail
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGTHSAIL_IP }}
          username: ${{ secrets.LIGTHSAIL_USERNAME }}
          key: ${{ secrets.LIGTHSAIL_KEY }}
          password: ""
          passphrase: ""
          port: 22
          script: |
            cd /var/www/html/
            git checkout -f 
            git pull
      - name: Deployment completed Successfully
        run: echo "Deployment completed successfuly"
